import type { ClothingCategory, StylePreference } from '@/types'

export interface CataloguePickItem {
  id: string
  label: string
  category: ClothingCategory
  subcategory: string
  imageUrl: string
  fallbackColor: string
  style: StylePreference[]
  colour: string
  tags: string[]
}

export const CATALOGUE_ITEMS: CataloguePickItem[] = [
  // ── TOPS ─────────────────────────────────────────────────────────────────
  {
    id: 'top-white-shirt',
    label: 'White Button-Down',
    category: 'tops',
    subcategory: 'shirts',
    imageUrl: 'https://images.unsplash.com/photo-1620799139507-2a76f79a2f4d?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#F5F3EF',
    style: ['classic', 'minimalist', 'business'],
    colour: 'White',
    tags: ['classic', 'versatile', 'crisp', 'office'],
  },
  {
    id: 'top-black-turtleneck',
    label: 'Black Turtleneck',
    category: 'tops',
    subcategory: 'knitwear',
    imageUrl: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#2B2B2B',
    style: ['minimalist', 'classic'],
    colour: 'Black',
    tags: ['minimalist', 'sleek', 'winter', 'layering'],
  },
  {
    id: 'top-striped-breton',
    label: 'Striped Breton Top',
    category: 'tops',
    subcategory: 'tops',
    imageUrl: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#E8E4DE',
    style: ['classic', 'minimalist'],
    colour: 'Navy/White',
    tags: ['nautical', 'classic', 'effortless', 'casual'],
  },
  {
    id: 'top-cream-knit',
    label: 'Cream Knit Sweater',
    category: 'tops',
    subcategory: 'knitwear',
    imageUrl: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#F4EDD5',
    style: ['minimalist', 'classic', 'bohemian'],
    colour: 'Cream',
    tags: ['cozy', 'soft', 'neutral', 'layering'],
  },
  {
    id: 'top-silk-blouse',
    label: 'Silk Blouse',
    category: 'tops',
    subcategory: 'blouses',
    imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#DDD5C8',
    style: ['romantic', 'classic', 'business'],
    colour: 'Blush',
    tags: ['elegant', 'feminine', 'silky', 'evening'],
  },
  {
    id: 'top-graphic-tee',
    label: 'Graphic Tee',
    category: 'tops',
    subcategory: 'tshirts',
    imageUrl: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#C8C8C8',
    style: ['streetwear', 'eclectic'],
    colour: 'White',
    tags: ['casual', 'cool', 'street', 'expressive'],
  },

  // ── BOTTOMS ───────────────────────────────────────────────────────────────
  {
    id: 'bottom-straight-jeans',
    label: 'Straight-Leg Jeans',
    category: 'bottoms',
    subcategory: 'jeans',
    imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#4A5B6F',
    style: ['classic', 'minimalist', 'streetwear'],
    colour: 'Blue',
    tags: ['everyday', 'denim', 'classic', 'versatile'],
  },
  {
    id: 'bottom-wide-trousers',
    label: 'Wide-Leg Trousers',
    category: 'bottoms',
    subcategory: 'trousers',
    imageUrl: 'https://images.unsplash.com/photo-1584865288642-42078afe6942?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#C9B08A',
    style: ['minimalist', 'business', 'classic'],
    colour: 'Camel',
    tags: ['tailored', 'chic', 'relaxed-fit', 'office'],
  },
  {
    id: 'bottom-mini-skirt',
    label: 'Mini Skirt',
    category: 'bottoms',
    subcategory: 'skirts',
    imageUrl: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#C8B4D4',
    style: ['romantic', 'eclectic', 'streetwear'],
    colour: 'Multi',
    tags: ['playful', 'flirty', 'bold', 'fun'],
  },
  {
    id: 'bottom-midi-skirt',
    label: 'Pleated Midi Skirt',
    category: 'bottoms',
    subcategory: 'skirts',
    imageUrl: 'https://images.unsplash.com/photo-1577900232427-18219b9166a0?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#F2D0D0',
    style: ['romantic', 'classic', 'bohemian'],
    colour: 'Dusty Rose',
    tags: ['feminine', 'flowy', 'elegant', 'effortless'],
  },
  {
    id: 'bottom-cargo-pants',
    label: 'Cargo Pants',
    category: 'bottoms',
    subcategory: 'trousers',
    imageUrl: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#8A9070',
    style: ['streetwear', 'eclectic', 'athleisure'],
    colour: 'Olive',
    tags: ['utility', 'relaxed', 'functional', 'street'],
  },
  {
    id: 'bottom-linen-pants',
    label: 'Linen Trousers',
    category: 'bottoms',
    subcategory: 'trousers',
    imageUrl: 'https://images.unsplash.com/photo-1560243563-062bfc001d68?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#E8DFC8',
    style: ['minimalist', 'bohemian', 'classic'],
    colour: 'Cream',
    tags: ['breezy', 'relaxed', 'summer', 'effortless'],
  },

  // ── DRESSES ───────────────────────────────────────────────────────────────
  {
    id: 'dress-slip',
    label: 'Silk Slip Dress',
    category: 'dresses',
    subcategory: 'slip-dresses',
    imageUrl: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#D4C9BE',
    style: ['minimalist', 'romantic', 'classic'],
    colour: 'Champagne',
    tags: ['sensual', 'minimal', 'evening', 'date-night'],
  },
  {
    id: 'dress-lbd',
    label: 'Little Black Dress',
    category: 'dresses',
    subcategory: 'cocktail',
    imageUrl: 'https://images.unsplash.com/photo-1514996937319-344454492b37?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#1F1F1F',
    style: ['classic', 'romantic', 'business'],
    colour: 'Black',
    tags: ['timeless', 'elegant', 'versatile', 'chic'],
  },
  {
    id: 'dress-floral-midi',
    label: 'Floral Midi Dress',
    category: 'dresses',
    subcategory: 'midi',
    imageUrl: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#C9B89A',
    style: ['bohemian', 'romantic', 'eclectic'],
    colour: 'Multi',
    tags: ['floral', 'summer', 'whimsical', 'feminine'],
  },
  {
    id: 'dress-shirt-dress',
    label: 'Shirt Dress',
    category: 'dresses',
    subcategory: 'shirt-dresses',
    imageUrl: 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#E8E4DE',
    style: ['classic', 'minimalist', 'business'],
    colour: 'White',
    tags: ['crisp', 'polished', 'casual-chic', 'day-to-night'],
  },
  {
    id: 'dress-knit',
    label: 'Knit Midi Dress',
    category: 'dresses',
    subcategory: 'knit',
    imageUrl: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#C4B5A5',
    style: ['minimalist', 'classic', 'romantic'],
    colour: 'Taupe',
    tags: ['cozy', 'understated', 'autumn', 'effortless'],
  },

  // ── OUTERWEAR ─────────────────────────────────────────────────────────────
  {
    id: 'coat-camel',
    label: 'Camel Wool Coat',
    category: 'outerwear',
    subcategory: 'coats',
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#C9A96E',
    style: ['classic', 'business', 'minimalist'],
    colour: 'Camel',
    tags: ['investment', 'luxury', 'timeless', 'winter'],
  },
  {
    id: 'jacket-leather',
    label: 'Leather Jacket',
    category: 'outerwear',
    subcategory: 'jackets',
    imageUrl: 'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#2C1F0E',
    style: ['streetwear', 'eclectic', 'classic'],
    colour: 'Black',
    tags: ['edgy', 'cool', 'iconic', 'statement'],
  },
  {
    id: 'blazer-white',
    label: 'Tailored Blazer',
    category: 'outerwear',
    subcategory: 'blazers',
    imageUrl: 'https://images.unsplash.com/photo-1580657018950-c7f7d6a6d990?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#F0EDE8',
    style: ['classic', 'business', 'minimalist', 'streetwear'],
    colour: 'White',
    tags: ['power-dressing', 'versatile', 'polished', 'office'],
  },
  {
    id: 'coat-trench',
    label: 'Trench Coat',
    category: 'outerwear',
    subcategory: 'coats',
    imageUrl: 'https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#C9B89A',
    style: ['classic', 'business', 'minimalist'],
    colour: 'Camel',
    tags: ['iconic', 'rain', 'polished', 'timeless'],
  },
  {
    id: 'jacket-denim',
    label: 'Denim Jacket',
    category: 'outerwear',
    subcategory: 'jackets',
    imageUrl: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#6B7A8D',
    style: ['streetwear', 'bohemian', 'classic'],
    colour: 'Blue',
    tags: ['casual', 'layering', 'weekend', 'denim'],
  },

  // ── SHOES ─────────────────────────────────────────────────────────────────
  {
    id: 'shoes-white-sneakers',
    label: 'White Sneakers',
    category: 'shoes',
    subcategory: 'sneakers',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#F5F5F5',
    style: ['minimalist', 'streetwear', 'athleisure'],
    colour: 'White',
    tags: ['clean', 'casual', 'everyday', 'versatile'],
  },
  {
    id: 'shoes-block-heels',
    label: 'Block Heel Pumps',
    category: 'shoes',
    subcategory: 'heels',
    imageUrl: 'https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#1F1F1F',
    style: ['classic', 'business', 'romantic'],
    colour: 'Black',
    tags: ['polished', 'office', 'evening', 'elegant'],
  },
  {
    id: 'shoes-ankle-boots',
    label: 'Ankle Boots',
    category: 'shoes',
    subcategory: 'boots',
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#3D2B1F',
    style: ['classic', 'streetwear', 'eclectic'],
    colour: 'Brown',
    tags: ['autumn', 'versatile', 'cool', 'grounded'],
  },
  {
    id: 'shoes-loafers',
    label: 'Leather Loafers',
    category: 'shoes',
    subcategory: 'loafers',
    imageUrl: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#7B5C3D',
    style: ['classic', 'business', 'minimalist'],
    colour: 'Tan',
    tags: ['smart-casual', 'preppy', 'comfortable', 'refined'],
  },
  {
    id: 'shoes-strappy-sandals',
    label: 'Strappy Sandals',
    category: 'shoes',
    subcategory: 'sandals',
    imageUrl: 'https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#C9A96E',
    style: ['romantic', 'bohemian', 'eclectic'],
    colour: 'Gold',
    tags: ['summer', 'feminine', 'vacation', 'evening'],
  },
  {
    id: 'shoes-chunky-boots',
    label: 'Chunky Platform Boots',
    category: 'shoes',
    subcategory: 'boots',
    imageUrl: 'https://images.unsplash.com/photo-1605812860427-4024433a70fd?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#1F1F1F',
    style: ['streetwear', 'eclectic'],
    colour: 'Black',
    tags: ['bold', 'statement', 'edgy', 'power'],
  },

  // ── ACCESSORIES ───────────────────────────────────────────────────────────
  {
    id: 'acc-mini-bag',
    label: 'Mini Leather Bag',
    category: 'accessories',
    subcategory: 'bags',
    imageUrl: 'https://images.unsplash.com/photo-1611923134239-b9be5816e23c?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#C4A882',
    style: ['classic', 'romantic', 'business'],
    colour: 'Tan',
    tags: ['chic', 'compact', 'evening', 'polished'],
  },
  {
    id: 'acc-sunglasses',
    label: 'Oversized Sunglasses',
    category: 'accessories',
    subcategory: 'eyewear',
    imageUrl: 'https://images.unsplash.com/photo-1577803645773-f96470509666?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#1F1F1F',
    style: ['classic', 'streetwear', 'minimalist'],
    colour: 'Black',
    tags: ['cool', 'statement', 'summer', 'iconic'],
  },
  {
    id: 'acc-silk-scarf',
    label: 'Silk Scarf',
    category: 'accessories',
    subcategory: 'scarves',
    imageUrl: 'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#F2D0A0',
    style: ['classic', 'romantic', 'bohemian', 'eclectic'],
    colour: 'Multi',
    tags: ['vintage', 'Parisian', 'elegant', 'versatile'],
  },
  {
    id: 'acc-watch',
    label: 'Minimalist Watch',
    category: 'accessories',
    subcategory: 'watches',
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#C9B89A',
    style: ['minimalist', 'classic', 'business'],
    colour: 'Gold',
    tags: ['investment', 'refined', 'everyday', 'understated'],
  },
  {
    id: 'acc-pearl-earrings',
    label: 'Pearl Earrings',
    category: 'accessories',
    subcategory: 'jewellery',
    imageUrl: 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#F5F0E8',
    style: ['classic', 'romantic', 'business'],
    colour: 'White',
    tags: ['timeless', 'elegant', 'subtle', 'polish'],
  },
  {
    id: 'acc-tote-bag',
    label: 'Canvas Tote',
    category: 'accessories',
    subcategory: 'bags',
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&q=80&auto=format&fit=crop',
    fallbackColor: '#E8DFC8',
    style: ['minimalist', 'bohemian', 'streetwear'],
    colour: 'Natural',
    tags: ['casual', 'practical', 'everyday', 'relaxed'],
  },
]

export const CATALOGUE_CATEGORIES: { value: ClothingCategory | 'all'; label: string }[] = [
  { value: 'all', label: 'All' },
  { value: 'tops', label: 'Tops' },
  { value: 'bottoms', label: 'Bottoms' },
  { value: 'dresses', label: 'Dresses' },
  { value: 'outerwear', label: 'Outerwear' },
  { value: 'shoes', label: 'Shoes' },
  { value: 'accessories', label: 'Accessories' },
]
