import type { CatalogItem, ClothingCategory } from '@/types'

type RawCatalogItem = Omit<CatalogItem, 'imageUrl' | 'estimatedPrice' | 'rentPricePerWeek' | 'shopUrl' | 'rentUrl'>

const RAW_CATALOG_ITEMS: RawCatalogItem[] = [
  // ─── Tops ────────────────────────────────────────────────────────────────────
  {
    id: 'cat-top-001',
    name: 'Classic White Oxford Shirt',
    category: 'tops',
    subcategory: 'Shirt',
    colours: ['White'],
    material: 'Cotton',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['work', 'casual', 'formal'],
    styleAesthetics: ['classic', 'business'],
    description: 'A wardrobe cornerstone. Crisp poplin cotton with a tailored fit that works dressed up or down.',
    priceRange: 'mid',
    fit: 'Regular',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-top-002',
    name: 'Black Ribbed Turtleneck',
    category: 'tops',
    subcategory: 'Sweatshirt',
    colours: ['Black'],
    material: 'Wool',
    pattern: 'solid',
    seasons: ['autumn', 'winter'],
    occasions: ['work', 'casual', 'date-night', 'formal'],
    styleAesthetics: ['minimalist', 'classic'],
    description: 'Elevated minimalism. Fine-knit merino wool with a slim silhouette that pairs with everything.',
    priceRange: 'premium',
    fit: 'Slim',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-top-003',
    name: 'Ivory Silk Blouse',
    category: 'tops',
    subcategory: 'Blouse',
    colours: ['Cream'],
    material: 'Silk',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['work', 'date-night', 'formal', 'special-event'],
    styleAesthetics: ['romantic', 'classic'],
    description: 'Understated luxury. Fluid silk with a relaxed drape that moves beautifully.',
    priceRange: 'premium',
    fit: 'Relaxed',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-top-004',
    name: 'Navy Breton Stripe Tee',
    category: 'tops',
    subcategory: 'T-shirt',
    colours: ['Navy', 'White'],
    material: 'Cotton',
    pattern: 'striped',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['casual', 'weekend', 'travel'],
    styleAesthetics: ['classic'],
    description: 'The Parisian staple. Heavyweight jersey with heritage breton stripes.',
    priceRange: 'mid',
    fit: 'Regular',
    formality: 'Casual',
  },
  {
    id: 'cat-top-005',
    name: 'Camel Cashmere Crew Neck',
    category: 'tops',
    subcategory: 'Sweatshirt',
    colours: ['Camel'],
    material: 'Cashmere',
    pattern: 'solid',
    seasons: ['autumn', 'winter'],
    occasions: ['work', 'casual', 'weekend'],
    styleAesthetics: ['classic', 'minimalist'],
    description: 'Everyday luxury. Pure cashmere with a relaxed crew neck that improves with every wear.',
    priceRange: 'luxury',
    fit: 'Regular',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-top-006',
    name: 'White Linen Oversized Shirt',
    category: 'tops',
    subcategory: 'Shirt',
    colours: ['White'],
    material: 'Linen',
    pattern: 'solid',
    seasons: ['spring', 'summer'],
    occasions: ['casual', 'weekend', 'travel'],
    styleAesthetics: ['minimalist', 'bohemian'],
    description: 'Summer ease. Relaxed linen that gets better with every wash.',
    priceRange: 'mid',
    fit: 'Oversized',
    formality: 'Casual',
  },
  {
    id: 'cat-top-007',
    name: 'Grey Marl Fitted Tee',
    category: 'tops',
    subcategory: 'T-shirt',
    colours: ['Grey'],
    material: 'Cotton',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['casual', 'weekend', 'gym'],
    styleAesthetics: ['minimalist', 'streetwear'],
    description: 'The perfect grey tee. Heavyweight cotton in a flattering fitted cut.',
    priceRange: 'budget',
    fit: 'Fitted',
    formality: 'Casual',
  },
  {
    id: 'cat-top-008',
    name: 'Forest Green Silk Camisole',
    category: 'tops',
    subcategory: 'Tank Top',
    colours: ['Forest Green'],
    material: 'Silk',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['date-night', 'casual', 'special-event'],
    styleAesthetics: ['romantic', 'minimalist'],
    description: 'Rich colour, effortless drape. Works alone or layered under a blazer.',
    priceRange: 'premium',
    fit: 'Fitted',
    formality: 'Smart Casual',
  },

  // ─── Bottoms ─────────────────────────────────────────────────────────────────
  {
    id: 'cat-bot-001',
    name: 'Dark Wash Straight Jeans',
    category: 'bottoms',
    subcategory: 'Jeans',
    colours: ['Charcoal'],
    material: 'Denim',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    occasions: ['casual', 'date-night', 'weekend', 'work'],
    styleAesthetics: ['classic', 'streetwear'],
    description: 'The forever jean. Dark indigo wash with a clean straight leg and no distressing.',
    priceRange: 'mid',
    fit: 'Regular',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-bot-002',
    name: 'Camel Wide-Leg Trousers',
    category: 'bottoms',
    subcategory: 'Trousers',
    colours: ['Camel'],
    material: 'Wool',
    pattern: 'solid',
    seasons: ['autumn', 'winter', 'spring'],
    occasions: ['work', 'formal', 'date-night'],
    styleAesthetics: ['classic', 'business'],
    description: 'Polished width. Fluid wool-blend with a high waist and sweeping wide leg.',
    priceRange: 'premium',
    fit: 'Relaxed',
    formality: 'Business',
  },
  {
    id: 'cat-bot-003',
    name: 'Black Tailored Trousers',
    category: 'bottoms',
    subcategory: 'Trousers',
    colours: ['Black'],
    material: 'Wool',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    occasions: ['work', 'formal', 'date-night'],
    styleAesthetics: ['business', 'minimalist', 'classic'],
    description: 'The essential black trouser. Sharp tailoring with a slight taper that flatters every frame.',
    priceRange: 'mid',
    fit: 'Slim',
    formality: 'Business',
  },
  {
    id: 'cat-bot-004',
    name: 'Beige Pleated Midi Skirt',
    category: 'bottoms',
    subcategory: 'Skirt',
    colours: ['Beige'],
    material: 'Cotton',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['casual', 'work', 'date-night'],
    styleAesthetics: ['classic', 'romantic'],
    description: 'Movement and elegance. Softly pleated cotton that flows beautifully with any top.',
    priceRange: 'mid',
    fit: 'Regular',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-bot-005',
    name: 'Cream Linen Wide-Leg Trousers',
    category: 'bottoms',
    subcategory: 'Trousers',
    colours: ['Cream'],
    material: 'Linen',
    pattern: 'solid',
    seasons: ['spring', 'summer'],
    occasions: ['casual', 'weekend', 'travel'],
    styleAesthetics: ['minimalist', 'classic', 'bohemian'],
    description: 'Summer sophistication. Relaxed linen cut with an easy wide leg.',
    priceRange: 'mid',
    fit: 'Relaxed',
    formality: 'Casual',
  },
  {
    id: 'cat-bot-006',
    name: 'Navy Tailored Linen Shorts',
    category: 'bottoms',
    subcategory: 'Shorts',
    colours: ['Navy'],
    material: 'Linen',
    pattern: 'solid',
    seasons: ['spring', 'summer'],
    occasions: ['casual', 'weekend', 'travel'],
    styleAesthetics: ['classic'],
    description: 'Refined shorts. Tailored linen with a polished silhouette that works beyond the beach.',
    priceRange: 'mid',
    fit: 'Regular',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-bot-007',
    name: 'Black Leather Pencil Skirt',
    category: 'bottoms',
    subcategory: 'Skirt',
    colours: ['Black'],
    material: 'Leather',
    pattern: 'solid',
    seasons: ['autumn', 'winter', 'spring'],
    occasions: ['work', 'date-night', 'formal'],
    styleAesthetics: ['classic', 'business'],
    description: 'Edge meets polish. Sleek faux-leather with a knee-length cut that commands a room.',
    priceRange: 'mid',
    fit: 'Fitted',
    formality: 'Business',
  },

  // ─── Dresses ─────────────────────────────────────────────────────────────────
  {
    id: 'cat-drs-001',
    name: 'Forest Green Wrap Midi Dress',
    category: 'dresses',
    subcategory: 'Wrap Dress',
    colours: ['Forest Green'],
    material: 'Viscose',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['date-night', 'special-event', 'casual'],
    styleAesthetics: ['romantic', 'classic'],
    description: 'The dress that works everywhere. Deep wrap silhouette that flatters every body.',
    priceRange: 'mid',
    fit: 'Fitted',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-drs-002',
    name: 'Champagne Slip Dress',
    category: 'dresses',
    subcategory: 'Midi Dress',
    colours: ['Gold', 'Cream'],
    material: 'Silk',
    pattern: 'solid',
    seasons: ['spring', 'summer'],
    occasions: ['formal', 'date-night', 'special-event'],
    styleAesthetics: ['minimalist', 'romantic'],
    description: 'Pure, quiet luxury. Fluid silk-satin that drapes like water.',
    priceRange: 'premium',
    fit: 'Relaxed',
    formality: 'Formal',
  },
  {
    id: 'cat-drs-003',
    name: 'Sky Blue Shirt Dress',
    category: 'dresses',
    subcategory: 'Casual Dress',
    colours: ['Sky Blue'],
    material: 'Cotton',
    pattern: 'solid',
    seasons: ['spring', 'summer'],
    occasions: ['casual', 'work', 'weekend'],
    styleAesthetics: ['classic'],
    description: 'Easy days, effortlessly put together. Crisp cotton in a flattering belted cut.',
    priceRange: 'mid',
    fit: 'Regular',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-drs-004',
    name: 'Black Wrap Midi Dress',
    category: 'dresses',
    subcategory: 'Wrap Dress',
    colours: ['Black'],
    material: 'Viscose',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    occasions: ['work', 'date-night', 'formal', 'special-event'],
    styleAesthetics: ['classic', 'minimalist'],
    description: 'The one dress that does everything. Sleek wrap with a midi hem that transitions seamlessly.',
    priceRange: 'mid',
    fit: 'Fitted',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-drs-005',
    name: 'White Broderie Midi Dress',
    category: 'dresses',
    subcategory: 'Midi Dress',
    colours: ['White'],
    material: 'Cotton',
    pattern: 'floral',
    seasons: ['spring', 'summer'],
    occasions: ['casual', 'weekend', 'special-event'],
    styleAesthetics: ['romantic', 'bohemian'],
    description: 'Warm-weather joy. Delicate broderie anglaise with a flattering A-line midi hem.',
    priceRange: 'mid',
    fit: 'Regular',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-drs-006',
    name: 'Camel Blazer Dress',
    category: 'dresses',
    subcategory: 'Casual Dress',
    colours: ['Camel'],
    material: 'Wool',
    pattern: 'solid',
    seasons: ['autumn', 'winter'],
    occasions: ['work', 'formal'],
    styleAesthetics: ['business', 'classic'],
    description: 'Office-ready in a single piece. Structured blazer-dress with belt-tie waist.',
    priceRange: 'premium',
    fit: 'Fitted',
    formality: 'Business',
  },

  // ─── Outerwear ───────────────────────────────────────────────────────────────
  {
    id: 'cat-out-001',
    name: 'Camel Wool Overcoat',
    category: 'outerwear',
    subcategory: 'Coat',
    colours: ['Camel'],
    material: 'Wool',
    pattern: 'solid',
    seasons: ['autumn', 'winter'],
    occasions: ['work', 'formal', 'casual', 'date-night'],
    styleAesthetics: ['classic'],
    description: 'The coat that never dates. Double-faced wool in warm camel with a clean, sweeping silhouette.',
    priceRange: 'luxury',
    fit: 'Relaxed',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-out-002',
    name: 'Navy Single-Breasted Blazer',
    category: 'outerwear',
    subcategory: 'Blazer',
    colours: ['Navy'],
    material: 'Wool',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    occasions: ['work', 'formal', 'date-night', 'casual'],
    styleAesthetics: ['business', 'classic'],
    description: 'The great equaliser. Impeccably tailored navy wool that sharpens any outfit.',
    priceRange: 'premium',
    fit: 'Slim',
    formality: 'Business',
  },
  {
    id: 'cat-out-003',
    name: 'Black Leather Biker Jacket',
    category: 'outerwear',
    subcategory: 'Leather Jacket',
    colours: ['Black'],
    material: 'Leather',
    pattern: 'solid',
    seasons: ['spring', 'autumn'],
    occasions: ['casual', 'date-night', 'weekend'],
    styleAesthetics: ['streetwear'],
    description: 'The rule-breaker. Real leather with asymmetric zip and just the right weight.',
    priceRange: 'premium',
    fit: 'Regular',
    formality: 'Casual',
  },
  {
    id: 'cat-out-004',
    name: 'Classic Beige Trench Coat',
    category: 'outerwear',
    subcategory: 'Coat',
    colours: ['Beige'],
    material: 'Cotton',
    pattern: 'solid',
    seasons: ['spring', 'autumn'],
    occasions: ['work', 'casual', 'travel', 'date-night'],
    styleAesthetics: ['classic'],
    description: 'The original. Belted trench in warm beige gabardine — unchanged since 1914 for good reason.',
    priceRange: 'premium',
    fit: 'Regular',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-out-005',
    name: 'Cream Oversized Blazer',
    category: 'outerwear',
    subcategory: 'Blazer',
    colours: ['Cream'],
    material: 'Cotton',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['work', 'date-night', 'casual'],
    styleAesthetics: ['minimalist', 'classic'],
    description: 'The modern blazer. Oversized cream cotton with clean lines and a relaxed, confident shape.',
    priceRange: 'mid',
    fit: 'Oversized',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-out-006',
    name: 'Indigo Denim Jacket',
    category: 'outerwear',
    subcategory: 'Jacket',
    colours: ['Cobalt'],
    material: 'Denim',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['casual', 'weekend', 'travel'],
    styleAesthetics: ['streetwear', 'classic'],
    description: 'The casual constant. Rigid indigo denim that softens beautifully over time.',
    priceRange: 'mid',
    fit: 'Regular',
    formality: 'Casual',
  },

  // ─── Shoes ───────────────────────────────────────────────────────────────────
  {
    id: 'cat-sho-001',
    name: 'White Leather Sneakers',
    category: 'shoes',
    subcategory: 'Sneakers',
    colours: ['White'],
    material: 'Leather',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['casual', 'weekend', 'travel'],
    styleAesthetics: ['minimalist', 'streetwear'],
    description: 'Clean, clean, clean. Full-grain leather with a low profile and no branding fuss.',
    priceRange: 'mid',
    formality: 'Casual',
  },
  {
    id: 'cat-sho-002',
    name: 'Black Leather Ankle Boots',
    category: 'shoes',
    subcategory: 'Boots',
    colours: ['Black'],
    material: 'Leather',
    pattern: 'solid',
    seasons: ['autumn', 'winter', 'spring'],
    occasions: ['work', 'date-night', 'casual', 'weekend'],
    styleAesthetics: ['classic', 'streetwear'],
    description: 'The year-round boot. Sleek block heel that works with dresses, trousers, or jeans.',
    priceRange: 'premium',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-sho-003',
    name: 'Tan Block Heel Mules',
    category: 'shoes',
    subcategory: 'Mules',
    colours: ['Tan'],
    material: 'Leather',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['work', 'casual', 'date-night'],
    styleAesthetics: ['classic', 'minimalist'],
    description: 'Effortless elevation. A stable block heel in warm tan that pairs with everything.',
    priceRange: 'mid',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-sho-004',
    name: 'Black Patent Loafers',
    category: 'shoes',
    subcategory: 'Loafers',
    colours: ['Black'],
    material: 'Leather',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    occasions: ['work', 'casual', 'formal'],
    styleAesthetics: ['classic', 'business', 'streetwear'],
    description: 'The shape that bridges every dress code. High-shine patent in a collegiate silhouette.',
    priceRange: 'premium',
    formality: 'Business',
  },
  {
    id: 'cat-sho-005',
    name: 'Nude Pointed-Toe Flats',
    category: 'shoes',
    subcategory: 'Flats',
    colours: ['Beige'],
    material: 'Leather',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    occasions: ['work', 'casual', 'formal'],
    styleAesthetics: ['classic', 'minimalist'],
    description: 'The invisible shoe. Nude leather that elongates the leg and disappears into any outfit.',
    priceRange: 'mid',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-sho-006',
    name: 'Brown Leather Chelsea Boots',
    category: 'shoes',
    subcategory: 'Boots',
    colours: ['Brown'],
    material: 'Leather',
    pattern: 'solid',
    seasons: ['autumn', 'winter', 'spring'],
    occasions: ['work', 'casual', 'weekend'],
    styleAesthetics: ['classic', 'streetwear'],
    description: 'The original ankle boot. Rich brown leather with elastic gussets that keep their shape.',
    priceRange: 'premium',
    formality: 'Smart Casual',
  },

  // ─── Accessories ─────────────────────────────────────────────────────────────
  {
    id: 'cat-acc-001',
    name: 'Structured Tan Tote',
    category: 'accessories',
    subcategory: 'Bag',
    colours: ['Tan'],
    material: 'Leather',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    occasions: ['work', 'casual', 'travel'],
    styleAesthetics: ['classic', 'business'],
    description: 'The working bag. Full-grain leather with enough structure to hold its shape, enough room for your life.',
    priceRange: 'premium',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-acc-002',
    name: 'Black Leather Crossbody',
    category: 'accessories',
    subcategory: 'Bag',
    colours: ['Black'],
    material: 'Leather',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    occasions: ['casual', 'travel', 'date-night', 'weekend'],
    styleAesthetics: ['minimalist'],
    description: 'Hands-free freedom. Sleek black leather with adjustable strap and clean hardware.',
    priceRange: 'mid',
    formality: 'Casual',
  },
  {
    id: 'cat-acc-003',
    name: 'Gold Hoop Earrings',
    category: 'accessories',
    subcategory: 'Jewellery',
    colours: ['Gold'],
    material: 'Gold',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    occasions: ['work', 'casual', 'date-night', 'formal', 'special-event'],
    styleAesthetics: ['classic', 'minimalist'],
    description: 'The default earring. Medium hoops in warm gold that elevate any outfit without competing.',
    priceRange: 'mid',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-acc-004',
    name: 'Silk Scarf in Cream & Navy',
    category: 'accessories',
    subcategory: 'Scarf',
    colours: ['Cream', 'Navy'],
    material: 'Silk',
    pattern: 'geometric',
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    occasions: ['work', 'casual', 'travel', 'date-night'],
    styleAesthetics: ['classic', 'romantic'],
    description: 'The scarf that does it all — neck, hair, bag handle, pocket square. 100% silk twill.',
    priceRange: 'premium',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-acc-005',
    name: 'Brown Leather Belt',
    category: 'accessories',
    subcategory: 'Belt',
    colours: ['Brown'],
    material: 'Leather',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    occasions: ['work', 'casual'],
    styleAesthetics: ['classic'],
    description: 'The quiet detail that ties everything together. Full-grain leather with minimal gold hardware.',
    priceRange: 'mid',
    formality: 'Smart Casual',
  },
  {
    id: 'cat-acc-006',
    name: 'Tortoiseshell Sunglasses',
    category: 'accessories',
    subcategory: 'Sunglasses',
    colours: ['Brown'],
    material: 'Acetate',
    pattern: 'solid',
    seasons: ['spring', 'summer'],
    occasions: ['casual', 'weekend', 'travel'],
    styleAesthetics: ['classic', 'eclectic'],
    description: 'The frame that flatters all faces. Warm tortoiseshell acetate in a timeless oversized silhouette.',
    priceRange: 'mid',
    formality: 'Casual',
  },
]

// ─── Enrichment ─────────────────────────────────────────────────────────────
// The raw catalog above only has descriptive fields. Photos, buy/rent prices,
// and shop links are derived here instead of hand-typed per item (62+
// entries), which would be both tedious and inconsistent.

// Reference photos, grouped by category and visually spot-checked (real
// Unsplash IDs do go dead over time — several of the ones originally reused
// from the onboarding catalogue had already 404'd). Reused across items
// within a category since this is mock/demo inspiration, not real inventory.
// Every ID below was visually spot-checked (not just load-tested) in-browser —
// several IDs originally reused from the onboarding catalogue loaded fine
// (200 OK) but turned out to depict a chair, a magazine storefront, a
// bathroom sink, and — memorably — a parrot. A 200 response only proves the
// URL resolves, not that the photo is remotely relevant, so don't add to
// these pools without opening the image first.
//
// Each entry also carries the colour(s) actually visible in that photo, so
// assignment can prefer a colour-matching image over blindly cycling through
// the pool — a plain cycle was putting a black tee on a "White Linen
// Oversized Shirt" and a blue chambray shirt on a "Black Ribbed Turtleneck".
interface PoolImage {
  id: string
  colours: string[]
}

const CATEGORY_IMAGE_POOL: Record<ClothingCategory, PoolImage[]> = {
  tops: [
    { id: 'photo-1602810318383-e386cc2a3ccf', colours: ['grey', 'blue'] },
    { id: 'photo-1596755094514-f87e34085b2c', colours: ['blue', 'navy', 'cobalt'] },
    { id: 'photo-1620799140408-edc6dcb6d633', colours: ['white', 'cream'] },
    { id: 'photo-1620799139507-2a76f79a2f4d', colours: ['white', 'cream'] },
    { id: 'photo-1554568218-0f1715e72254', colours: ['white', 'cream'] },
    { id: 'photo-1618354691373-d851c5c3a990', colours: ['black', 'charcoal'] },
    { id: 'photo-1571945153237-4929e783af4a', colours: ['white', 'cream'] },
    { id: 'photo-1583743814966-8936f5b7be1a', colours: ['white', 'cream'] },
    { id: 'photo-1562157873-818bc0726f68', colours: ['white', 'navy', 'burgundy'] },
    { id: 'photo-1622445275463-afa2ab738c34', colours: ['white', 'cream'] },
    { id: 'photo-1521572163474-6864f9cf17ab', colours: ['white', 'cream'] },
    { id: 'photo-1490481651871-ab68de25d43d', colours: ['white', 'cream', 'beige'] },
  ],
  bottoms: [
    { id: 'photo-1541099649105-f69ad21f3246', colours: ['blue', 'cobalt'] },
    { id: 'photo-1594633312681-425c7b97ccd1', colours: ['blush', 'dusty rose'] },
    { id: 'photo-1584865288642-42078afe6942', colours: ['black', 'charcoal'] },
    { id: 'photo-1560243563-062bfc001d68', colours: ['blue', 'cobalt', 'navy'] },
    { id: 'photo-1583496661160-fb5886a0aaaa', colours: ['black', 'charcoal'] },
    { id: 'photo-1577900232427-18219b9166a0', colours: ['white', 'cream', 'beige'] },
  ],
  dresses: [
    { id: 'photo-1496747611176-843222e1e57c', colours: ['gold', 'cream', 'beige'] },
    { id: 'photo-1514996937319-344454492b37', colours: ['black', 'charcoal'] },
    { id: 'photo-1591369822096-ffd140ec948f', colours: ['sky blue', 'blue'] },
    { id: 'photo-1595777457583-95e059d581b8', colours: ['rust', 'terracotta'] },
    { id: 'photo-1566174053879-31528523f8ae', colours: ['plum', 'lavender'] },
  ],
  outerwear: [
    { id: 'photo-1551028719-00167b16eac5', colours: ['camel', 'tan', 'beige'] },
    { id: 'photo-1560769629-975ec94e6a86', colours: ['blue', 'cobalt', 'navy'] },
    { id: 'photo-1591047139829-d91aecb6caea', colours: ['camel', 'tan'] },
    { id: 'photo-1544022613-e87ca75a784a', colours: ['olive', 'forest green', 'sage'] },
    { id: 'photo-1520975954732-35dd22299614', colours: ['black', 'charcoal'] },
    { id: 'photo-1521223890158-f9f7c3d5d504', colours: ['black', 'charcoal'] },
    { id: 'photo-1487222477894-8943e31ef7b2', colours: ['camel', 'tan', 'beige'] },
  ],
  shoes: [
    { id: 'photo-1542291026-7eec264c27ff', colours: ['rust', 'terracotta'] },
    { id: 'photo-1543163521-1bf539c55dd2', colours: ['navy', 'gold'] },
    { id: 'photo-1614252235316-8c857d38b5f4', colours: ['brown', 'tan'] },
    { id: 'photo-1515347619252-60a4bf4fff4f', colours: ['gold', 'tan'] },
    { id: 'photo-1605812860427-4024433a70fd', colours: ['brown', 'black'] },
  ],
  accessories: [
    { id: 'photo-1523275335684-37898b6baf30', colours: ['black', 'silver'] },
    { id: 'photo-1611085583191-a3b181a88401', colours: ['gold', 'white'] },
    { id: 'photo-1544816155-12df9643f363', colours: ['brown', 'tan'] },
    { id: 'photo-1591561954557-26941169b49e', colours: ['gold', 'cream'] },
    { id: 'photo-1611923134239-b9be5816e23c', colours: ['black'] },
    { id: 'photo-1577803645773-f96470509666', colours: ['brown', 'tan'] },
  ],
}

// Buy/rent price bands per price tier (USD). Rent is priced per week, at
// roughly 8-12% of the buy price, the way real rental marketplaces price
// against retail value.
// Indian retail price points, in rupees.
const PRICE_BAND: Record<CatalogItem['priceRange'], [number, number]> = {
  budget: [999, 2400],
  mid: [2500, 5900],
  premium: [6000, 14500],
  luxury: [15000, 40000],
}

// Small deterministic hash so the same item always gets the same "random"
// price/image pick — stable across renders and reloads.
function hashString(s: string): number {
  let h = 0
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0
  return h
}

function enrichCatalogItem(item: RawCatalogItem, categoryIndex: number): CatalogItem {
  const pool = CATEGORY_IMAGE_POOL[item.category]
  const itemColours = item.colours.map((c) => c.toLowerCase())

  // Prefer a photo whose visible colour actually overlaps the item's stated
  // colour(s) over blindly cycling the pool — that's what put a black tee
  // under "White Linen Oversized Shirt" and a blue shirt under "Black
  // Ribbed Turtleneck". Among equally-good matches, cycle by category index
  // so items don't all collapse onto the single best-matching photo.
  const scored = pool.map((img) => ({
    img,
    score: img.colours.some((c) => itemColours.includes(c)) ? 1 : 0,
  }))
  const bestScore = Math.max(...scored.map((s) => s.score))
  const candidates = scored.filter((s) => s.score === bestScore)
  const chosen = candidates[categoryIndex % candidates.length].img
  const imageUrl = `https://images.unsplash.com/${chosen.id}?w=600&q=80&auto=format&fit=crop`

  const hash = hashString(item.id)
  const [lo, hi] = PRICE_BAND[item.priceRange]
  // Rounded to a retail-style ₹x,x99 price, and a weekly rental of ~8–12% (min ₹299).
  const estimatedPrice = Math.round((lo + (hash % 100) / 100 * (hi - lo)) / 100) * 100 - 1
  const rentPricePerWeek = Math.max(299, Math.round((estimatedPrice * (0.08 + (hash % 40) / 1000)) / 50) * 50 - 1)

  const query = encodeURIComponent(`${item.name} ${item.material}`)
  const shopUrl = `https://www.google.com/search?tbm=shop&q=${query}`
  const rentUrl = `https://www.google.com/search?q=${encodeURIComponent(`rent ${item.name}`)}`

  return { ...item, imageUrl, estimatedPrice, rentPricePerWeek, shopUrl, rentUrl }
}

const categoryCounters: Partial<Record<ClothingCategory, number>> = {}

export const CATALOG_ITEMS: CatalogItem[] = RAW_CATALOG_ITEMS.map((item) => {
  const idx = categoryCounters[item.category] ?? 0
  categoryCounters[item.category] = idx + 1
  return enrichCatalogItem(item, idx)
})

export const CATALOG_STYLE_LABELS: Record<string, string> = {
  classic: 'Classic',
  minimalist: 'Minimalist',
  business: 'Business',
  streetwear: 'Streetwear',
  bohemian: 'Bohemian',
  athleisure: 'Athleisure',
  romantic: 'Romantic',
  eclectic: 'Eclectic',
}

export const CATALOG_PRICE_LABELS: Record<string, string> = {
  budget: 'Budget',
  mid: 'Mid-range',
  premium: 'Premium',
  luxury: 'Luxury',
}
