import type { ClothingItem } from '@/types'

const now = new Date().toISOString()

function makeId() {
  return Math.random().toString(36).slice(2, 10)
}

export const SAMPLE_WARDROBE_ITEMS: ClothingItem[] = [
  {
    id: makeId(),
    name: 'White Button-Down Shirt',
    category: 'tops',
    imageUrl: null,
    imageSource: 'none',
    colour: ['White'],
    material: 'Cotton',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['work', 'casual', 'formal'],
    brand: '',
    notes: '',
    isFavourite: true,
    timesWorn: 12,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId(),
    name: 'Navy Blazer',
    category: 'outerwear',
    imageUrl: null,
    imageSource: 'none',
    colour: ['Navy'],
    material: 'Wool blend',
    pattern: 'solid',
    seasons: ['spring', 'autumn', 'winter'],
    occasions: ['work', 'formal', 'date-night'],
    brand: '',
    notes: '',
    isFavourite: true,
    timesWorn: 8,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId(),
    name: 'Black Tailored Trousers',
    category: 'bottoms',
    imageUrl: null,
    imageSource: 'none',
    colour: ['Black'],
    material: 'Wool blend',
    pattern: 'solid',
    seasons: ['all-season'],
    occasions: ['work', 'formal', 'date-night'],
    brand: '',
    notes: '',
    isFavourite: false,
    timesWorn: 15,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId(),
    name: 'Camel Wool Coat',
    category: 'outerwear',
    imageUrl: null,
    imageSource: 'none',
    colour: ['Camel'],
    material: 'Wool',
    pattern: 'solid',
    seasons: ['autumn', 'winter'],
    occasions: ['casual', 'work', 'special-event'],
    brand: '',
    notes: '',
    isFavourite: true,
    timesWorn: 6,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId(),
    name: 'Dark Wash Jeans',
    category: 'bottoms',
    imageUrl: null,
    imageSource: 'none',
    colour: ['Navy'],
    material: 'Denim',
    pattern: 'solid',
    seasons: ['all-season'],
    occasions: ['casual', 'weekend', 'date-night'],
    brand: '',
    notes: '',
    isFavourite: false,
    timesWorn: 22,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId(),
    name: 'Cream Silk Blouse',
    category: 'tops',
    imageUrl: null,
    imageSource: 'none',
    colour: ['Cream'],
    material: 'Silk',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['work', 'date-night', 'formal'],
    brand: '',
    notes: '',
    isFavourite: true,
    timesWorn: 7,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId(),
    name: 'Black Midi Dress',
    category: 'dresses',
    imageUrl: null,
    imageSource: 'none',
    colour: ['Black'],
    material: 'Jersey',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['work', 'date-night', 'special-event'],
    brand: '',
    notes: '',
    isFavourite: false,
    timesWorn: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId(),
    name: 'White Leather Trainers',
    category: 'shoes',
    imageUrl: null,
    imageSource: 'none',
    colour: ['White'],
    material: 'Leather',
    pattern: 'solid',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['casual', 'weekend'],
    brand: '',
    notes: '',
    isFavourite: false,
    timesWorn: 18,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId(),
    name: 'Grey Cashmere Sweater',
    category: 'tops',
    imageUrl: null,
    imageSource: 'none',
    colour: ['Grey'],
    material: 'Cashmere',
    pattern: 'solid',
    seasons: ['autumn', 'winter'],
    occasions: ['casual', 'weekend', 'work'],
    brand: '',
    notes: '',
    isFavourite: true,
    timesWorn: 9,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId(),
    name: 'Gold Hoop Earrings',
    category: 'accessories',
    imageUrl: null,
    imageSource: 'none',
    colour: ['Gold'],
    material: 'Gold-plated',
    pattern: 'solid',
    seasons: ['all-season'],
    occasions: ['work', 'casual', 'date-night', 'formal'],
    brand: '',
    notes: '',
    isFavourite: true,
    timesWorn: 30,
    createdAt: now,
    updatedAt: now,
  },
]
